# .github/workflows/deploy.yml

name: Deploy AI Interior Designer

on:
  push:
    branches: [ "main" ]

jobs:
  # 作业 1: 部署前端 (之前已配置)
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: touch frontend/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend
      - uses: actions/deploy-pages@v4

  # 作业 2: 新增 - 部署后端代理
  deploy-backend-proxy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - id: 'deploy'
        name: 'Deploy Cloud Function'
        uses: 'google-github-actions/deploy-cloud-functions@v2'
        with:
          name: 'ai-design-proxy' # 您的云函数名称
          runtime: 'nodejs18'
          source_dir: ./backend
          entry_point: 'handler' # 对应 backend/index.js 中导出的函数
          # 关键一步：安全地将 API 密钥设置为环境变量
          env_vars:
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
