name: Deploy AI Interior Designer

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: touch frontend/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend
      - uses: actions/deploy-pages@v4

  deploy-backend-proxy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - id: 'deploy'
        name: 'Deploy Cloud Function'
        uses: 'google-github-actions/deploy-cloud-functions@v2'
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          region: ${{ vars.GCP_REGION }}
          name: 'ai-design-proxy'
          runtime: 'nodejs18'
          source_dir: ./backend
          entry_point: 'handler'
          env_vars: GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}